# Generated by Django 4.2.5 on 2023-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Описание отсутствует'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
