# Generated by Django 4.2.5 on 2023-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_product_description_product_image_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='source/img/product_images/'),
        ),
    ]
