# Generated by Django 4.2.5 on 2023-09-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_product_duration_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy.product'),
        ),
    ]
